# Generated by Django 3.1.4 on 2021-07-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0037_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books', verbose_name='book image'),
        ),
    ]
